# SPDX-License-Identifier: MIT
# Copyright (c) 2026 sonde contributors

"""SPICE deck generator — builds ngspice-compatible .cir files.

Reads a netlist JSON and a test definition YAML, then emits a
self-contained ``.cir`` file that can be run with ``ngspice -b``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_MODELS_DIR = Path(__file__).resolve().parent / "models"
_TESTS_DIR = Path(__file__).resolve().parent / "tests"

# State name → ngspice STATE parameter value
_STATE_PARAM: dict[str, int] = {
    "deep_sleep": 0,
    "active": 1,
    "radio_tx": 2,
}


# ---------------------------------------------------------------------------
# Test loader
# ---------------------------------------------------------------------------

def load_test(test_id: str) -> dict[str, Any]:
    """Load a test definition YAML by its ``id``."""
    path = _TESTS_DIR / f"{test_id}.yaml"
    if not path.exists():
        raise FileNotFoundError(f"Test definition not found: {path}")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def list_tests() -> list[dict[str, Any]]:
    """Return all available test definitions."""
    tests = []
    for p in sorted(_TESTS_DIR.glob("*.yaml")):
        t = yaml.safe_load(p.read_text(encoding="utf-8"))
        tests.append(t)
    return tests


# ---------------------------------------------------------------------------
# Netlist loader
# ---------------------------------------------------------------------------

def load_netlist(path: Path) -> dict[str, Any]:
    """Load a netlist JSON file."""
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# SPICE deck generation
# ---------------------------------------------------------------------------

def _model_includes(netlist: dict) -> list[str]:
    """Determine which .include directives are needed."""
    models_needed: set[str] = set()
    for comp in netlist["components"]:
        m = comp.get("model", "")
        if m:
            models_needed.add(m)

    includes: list[str] = []
    model_files = {
        "mcp1700": _MODELS_DIR / "mcp1700.sub",
        "si2301": _MODELS_DIR / "si2301.mod",
        "schottky": _MODELS_DIR / "schottky.mod",
        "esp32c3": _MODELS_DIR / "esp32c3.sub",
        "usblc6": _MODELS_DIR / "usblc6.sub",
    }
    for m in sorted(models_needed):
        if m in model_files:
            includes.append(f'.include "{model_files[m]}"')
    return includes


def _parse_value(val_str: str) -> str:
    """Convert component value to SPICE-compatible format.

    Examples: ``10MΩ`` → ``10Meg``, ``4.7kΩ`` → ``4.7k``,
    ``100nF`` → ``100n``, ``1µF`` → ``1u``.
    """
    s = val_str.replace("Ω", "").replace("F", "").replace("H", "")
    s = s.replace("µ", "u")
    s = s.replace("M", "Meg") if s.endswith("M") or "MΩ" in val_str else s
    # Handle megaohm: "10MΩ" → "10M" → needs "10Meg"
    if "MΩ" in val_str:
        s = val_str.replace("MΩ", "Meg")
    elif "kΩ" in val_str:
        s = val_str.replace("kΩ", "k")
    elif "µF" in val_str:
        s = val_str.replace("µF", "u")
    elif "nF" in val_str:
        s = val_str.replace("nF", "n")
    elif "pF" in val_str:
        s = val_str.replace("pF", "p")
    elif "Ω" in val_str:
        s = val_str.replace("Ω", "")
    else:
        s = val_str
    return s


def _net_name_spice(name: str) -> str:
    """Sanitise a net name for SPICE (replace slashes, spaces)."""
    return name.replace("/", "_").replace(" ", "_")


def generate_deck(
    netlist: dict,
    test: dict,
    output_path: Path,
) -> Path:
    """Generate a SPICE deck ``.cir`` file.

    Returns the path to the generated file.
    """
    lines: list[str] = []
    test_id = test["id"]
    test_name = test.get("name", test_id)

    lines.append(f"* {test_name}")
    lines.append(f"* Auto-generated by sonde-hw simulate (test: {test_id})")
    lines.append("")

    # State parameter for ESP32 model
    state = test.get("state", "active")
    state_val = _STATE_PARAM.get(state, 1)
    lines.append(f".param STATE={state_val}")
    lines.append("")

    # Model includes
    for inc in _model_includes(netlist):
        lines.append(inc)
    lines.append("")

    # Source definitions
    sources = test.get("sources", {})

    if sources.get("VBAT", 0) > 0:
        lines.append(f"VBAT vbat_src 0 DC {sources['VBAT']}")
        # VBAT drives through schottky D2: K=VBAT, A=VIN
        # Model D2 inline since it's on the power path
        lines.append("D2 vbat_src vbat_reg schottky")
    else:
        # No battery — tie VBAT to ground
        lines.append("VBAT vbat_src 0 DC 0")
        lines.append("D2 vbat_src vbat_reg schottky")

    if sources.get("VUSB", 0) > 0:
        lines.append(f"VUSB vusb 0 DC {sources['VUSB']}")
        lines.append("D1 vusb vbat_reg schottky")
    else:
        lines.append("VUSB vusb 0 DC 0")
        lines.append("D1 vusb vbat_reg schottky")

    lines.append("")

    # LDO: MCP1700 subcircuit
    lines.append("* LDO regulator")
    lines.append("XU2 vbat_reg 0 v3v3 mcp1700")
    lines.append("")

    # ESP32-C3 current sink
    lines.append("* ESP32-C3 current sink")
    lines.append("XU1 v3v3 0 esp32c3")
    lines.append("")

    # USBLC6 ESD leakage
    lines.append("* USBLC6 ESD protection leakage")
    lines.append("XU3 usb_dp 0 usb_dn usb_dn_o vusb usb_dp_o usblc6")
    lines.append("")

    # Power gate: Si2301 P-FET (Q1)
    # Check if the netlist has a power gate
    has_power_gate = any(c["ref"] == "Q1" for c in netlist["components"])
    if has_power_gate:
        lines.append("* Power gate (Si2301 P-FET)")
        lines.append("* Gate driven low for ON; tied to 3V3 via R9 for default OFF")
        lines.append("MQ1 sensor_3v3 gate_q1 v3v3 v3v3 si2301 w=1 l=1u")
        lines.append("R9 v3v3 gate_q1 10k")
        lines.append("R10 gate_q1 sensor_pwr_en 10k")
        # In sleep, sensor gate is OFF (GPIO high-Z, R9 pulls gate to 3V3)
        if state == "deep_sleep":
            lines.append("Vgate sensor_pwr_en 0 DC 3.3")
        else:
            lines.append("Vgate sensor_pwr_en 0 DC 0")
        lines.append("")

    # Battery voltage divider
    has_divider = any(c["ref"] == "R11" for c in netlist["components"])
    if has_divider:
        lines.append("* Battery voltage divider")
        r11_val = "10Meg"
        r12_val = "10Meg"
        # Look up actual values from netlist
        for c in netlist["components"]:
            if c["ref"] == "R11":
                r11_val = _parse_value(c["value"])
            elif c["ref"] == "R12":
                r12_val = _parse_value(c["value"])
        lines.append(f"R11 vbat_src vbat_sense {r11_val}")
        lines.append(f"R12 vbat_sense 0 {r12_val}")
        # ADC filter cap
        has_c2 = any(c["ref"] == "C2" for c in netlist["components"])
        if has_c2:
            c2_val = "100p"
            for c in netlist["components"]:
                if c["ref"] == "C2":
                    c2_val = _parse_value(c["value"])
            lines.append(f"C2 vbat_sense 0 {c2_val}")
        lines.append("")

    # Decoupling / bypass caps on rails
    lines.append("* Decoupling capacitors")
    for c in netlist["components"]:
        if c["type"] == "capacitor" and c["ref"] not in ("C2",):
            val = _parse_value(c["value"])
            # Determine which rail this cap is on from pin nets
            pins = c.get("pins", {})
            pin1_net = pins.get("1", {}).get("net", "")
            pin2_net = pins.get("2", {}).get("net", "")
            n1 = _net_name_spice(pin1_net) if pin1_net else "0"
            n2 = _net_name_spice(pin2_net) if pin2_net else "0"
            # Map well-known net names to SPICE node names
            n1 = _map_net(n1)
            n2 = _map_net(n2)
            if n1 and n2:
                lines.append(f"{c['ref']} {n1} {n2} {val}")
    lines.append("")

    # Strapping / pull-up resistors (non-power-critical; include for accuracy)
    lines.append("* Pull-up and strapping resistors")
    for c in netlist["components"]:
        if c["type"] == "resistor" and c["ref"] not in ("R9", "R10", "R11", "R12"):
            val = _parse_value(c["value"])
            pins = c.get("pins", {})
            pin1_net = pins.get("1", {}).get("net", "")
            pin2_net = pins.get("2", {}).get("net", "")
            n1 = _map_net(_net_name_spice(pin1_net)) if pin1_net else "nc_" + c["ref"] + "_1"
            n2 = _map_net(_net_name_spice(pin2_net)) if pin2_net else "nc_" + c["ref"] + "_2"
            lines.append(f"{c['ref']} {n1} {n2} {val}")
    lines.append("")

    # I2C pull-ups draw negligible current; already included above as resistors

    # Analysis
    analysis = test.get("analysis", {})
    analysis_type = analysis.get("type", "op")
    if analysis_type == "op":
        lines.append(".op")
    elif analysis_type == "dc":
        params = analysis.get("params", "")
        lines.append(f".dc {params}")
    elif analysis_type == "tran":
        step = analysis.get("step", "1u")
        stop = analysis.get("stop", "10m")
        lines.append(f".tran {step} {stop}")
    lines.append("")

    # .measure statements for assertions
    lines.append("* Measurements for assertion evaluation")
    for i, assertion in enumerate(test.get("assertions", [])):
        meas_name = f"meas_{i}"
        measure_type = assertion.get("measure", "voltage")
        if measure_type == "voltage":
            net = assertion.get("net", "")
            spice_net = _map_net(_net_name_spice(net))
            if analysis_type == "op":
                # For .op, use .print instead of .measure
                pass  # handled via .print below
            lines.append(f"* assert[{i}]: {assertion.get('description', '')}")
        elif measure_type == "current":
            source = assertion.get("source", "")
            lines.append(f"* assert[{i}]: {assertion.get('description', '')}")

    # .print / .save for extracting values
    # For .op analysis, ngspice prints all node voltages
    lines.append("")
    lines.append("* Print key node voltages and source currents")
    lines.append(".control")
    lines.append("run")

    # Print measurements
    for i, assertion in enumerate(test.get("assertions", [])):
        measure_type = assertion.get("measure", "voltage")
        if measure_type == "voltage":
            net = assertion.get("net", "")
            spice_net = _map_net(_net_name_spice(net))
            lines.append(f'echo "MEAS meas_{i} =" $&v({spice_net})')
        elif measure_type == "current":
            source = assertion.get("source", "")
            # Current through a voltage source: I(Vsource)
            # ngspice: @vsource[i] or i(vsource)
            # The source name in our deck is "VBAT", "VUSB", etc.
            src_name = source.lower()
            lines.append(f'echo "MEAS meas_{i} =" $&i({src_name})')

    lines.append("quit")
    lines.append(".endc")
    lines.append("")
    lines.append(".end")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


def _map_net(name: str) -> str:
    """Map schematic net names to SPICE node names."""
    mapping = {
        "3V3": "v3v3",
        "GND": "0",
        "VBAT": "vbat_src",
        "VUSB": "vusb",
        "VIN": "vbat_reg",
        "VBAT_SENSE": "vbat_sense",
        "VBAT_REG": "vbat_reg",
        "SENSOR_3V3": "sensor_3v3",
        "SENSOR_PWR_EN": "sensor_pwr_en",
        "GATE_Q1": "gate_q1",
        "EN": "en",
        "BOOT": "boot",
        "GPIO1": "gpio1",
        "GPIO2": "gpio2",
        "GPIO6": "gpio6",
        "GPIO7": "gpio7",
        "GPIO8": "gpio8",
        "GPIO10": "gpio10",
        "GPIO20": "gpio20",
        "GPIO21": "gpio21",
        "USB_DP": "usb_dp",
        "USB_DN": "usb_dn",
        "CC1": "cc1",
        "CC2": "cc2",
        "I2C0_SDA": "i2c0_sda",
        "I2C0_SCL": "i2c0_scl",
    }
    return mapping.get(name, name.lower() if name else "0")
