# SPDX-License-Identifier: MIT
# Copyright (c) 2026 sonde contributors

"""KiCad schematic generator — composes templates into a .kicad_sch file."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from kiutils.items.common import Effects, Font, Position, Property, TitleBlock
from kiutils.items.schitems import LocalLabel, SchematicSymbol
from kiutils.schematic import Schematic
from kiutils.symbol import Symbol

from sonde_hw import __version__
from sonde_hw.config import BoardConfig
from sonde_hw.spice.netlist import (
    build_netlist,
    export_netlist_json,
)
from sonde_hw.templates import (
    RefAllocator,
    TemplateResult,
    UuidGenerator,
)
from sonde_hw.templates.base import template_base
from sonde_hw.templates.battery import template_battery
from sonde_hw.templates.gpio_header import template_gpio_header
from sonde_hw.templates.power_gate import template_power_gate
from sonde_hw.templates.qwiic import template_qwiic


FIXED_DATE = "2026-01-01"


def generate_schematic(config: BoardConfig, output_dir: Path) -> Path:
    """Generate a KiCad schematic for the given board configuration.

    Returns the path to the generated ``.kicad_sch`` file.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    sch_path = output_dir / "board.kicad_sch"

    uuid_gen = UuidGenerator(config.config_hash)
    ref_alloc = RefAllocator()

    # ---------------------------------------------------------------
    # Collect template results in fixed order.
    # All origin coordinates are multiples of 2.54 mm (100 mil) to
    # keep every pin endpoint on the KiCad connection grid.
    # ---------------------------------------------------------------
    G = 2.54  # grid unit
    results: list[TemplateResult] = []

    # 1. Base (always included)
    results.append(template_base(config, (0, 0), ref_alloc, uuid_gen))

    # 2. Power gate (if enabled)
    if config.power.get("sensor_gating"):
        results.append(template_power_gate(
            config, (67 * G, 12 * G), ref_alloc, uuid_gen,
        ))

    # 3. Battery (if enabled)
    if config.connectors.get("battery"):
        results.append(template_battery(
            config, (67 * G, 24 * G), ref_alloc, uuid_gen,
        ))

    # 4. Qwiic connectors
    num_qwiic = config.connectors.get("qwiic", 0)
    for i in range(num_qwiic):
        results.append(template_qwiic(
            config, (67 * G, (36 + i * 12) * G), ref_alloc, uuid_gen,
            instance_index=i,
        ))

    # 5. GPIO header (if enabled)
    if config.connectors.get("gpio_header"):
        results.append(template_gpio_header(
            config, (67 * G, 59 * G), ref_alloc, uuid_gen,
        ))

    # ---------------------------------------------------------------
    # Compose into a single schematic
    # ---------------------------------------------------------------
    sch = Schematic.create_new()
    sch.version = 20231120
    sch.generator = "sonde-hw"
    sch.uuid = uuid_gen.next("root")
    # paper is already PageSettings("A4") from create_new()

    # Title block
    tb = TitleBlock()
    tb.title = f"sonde — {config.name}"
    tb.date = FIXED_DATE
    tb.revision = __version__
    tb.comments = {
        1: f"Config hash: {config.config_hash}",
        2: f"Generated by sonde-hw {__version__}",
    }
    sch.titleBlock = tb

    # Merge lib_symbols (deduplicate by qualified name)
    seen_syms: dict[str, Symbol] = {}
    for r in results:
        for sym in r.lib_symbols:
            key = f"{sym.libraryNickname}:{sym.entryName}"
            if key not in seen_syms:
                seen_syms[key] = sym

    # Sort by name for determinism (HW-0900)
    sch.libSymbols = [seen_syms[k] for k in sorted(seen_syms)]

    # Merge instances (sort by reference designator)
    all_instances: list[SchematicSymbol] = []
    for r in results:
        all_instances.extend(r.instances)
    all_instances.sort(key=_ref_sort_key)
    sch.schematicSymbols = all_instances

    # Merge wires (sort by coordinates)
    all_wires = []
    for r in results:
        all_wires.extend(r.wires)
    all_wires.sort(key=lambda w: (
        min(p.X for p in w.points),
        min(p.Y for p in w.points),
    ))
    sch.graphicalItems = all_wires

    # Merge labels (sort by text then position)
    all_labels: list[LocalLabel] = []
    for r in results:
        all_labels.extend(r.labels)
    all_labels.sort(key=lambda lb: (lb.text, lb.position.X, lb.position.Y))
    sch.labels = all_labels

    # Write output — kiutils to_file may not use UTF-8 on Windows,
    # so we serialize to string and write with explicit encoding.
    sexpr = sch.to_sexpr()
    with open(str(sch_path), "w", encoding="utf-8") as f:
        f.write(sexpr)

    # Export netlist JSON (HW-SIM-001)
    netlist = build_netlist(
        config_name=config.name,
        lib_symbols=[seen_syms[k] for k in sorted(seen_syms)],
        instances=all_instances,
        labels=all_labels,
    )
    netlist_path = output_dir / "netlist.json"
    export_netlist_json(netlist, netlist_path)

    return sch_path


def _ref_sort_key(sym: SchematicSymbol) -> tuple[str, int]:
    """Sort key for reference designators: ('C', 1), ('R', 2), etc."""
    ref = ""
    for p in sym.properties:
        if p.key == "Reference":
            ref = p.value
            break
    prefix = ref.rstrip("0123456789")
    num_str = ref[len(prefix):]
    num = int(num_str) if num_str else 0
    return (prefix, num)
