[package]
name = "sonde-azure-handler"
edition = "2021"
version.workspace = true
license = "MIT"

[dependencies]
async-trait = "0.1"
axum = "0.8.9"
azservicebus = { version = "0.25.1", default-features = false, features = ["rustls"] }
azure_core = { version = "0.25.0", default-features = false }
azure_core_legacy = { package = "azure_core", version = "0.21.0", default-features = false }
azure_data_tables = "0.21.0"
azure_identity = { version = "0.25.0", default-features = false, features = ["reqwest_rustls", "tokio"] }
azure_identity_legacy = { package = "azure_identity", version = "0.21.0", default-features = false, features = ["enable_reqwest_rustls"] }
base64 = "0.22"
ciborium = "0.2"
futures = "0.3"
getrandom = "0.3"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
sonde-gateway = { path = "../sonde-gateway", default-features = false }
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[dev-dependencies]
tokio = { version = "1", features = ["test-util"] }
