// SPDX-License-Identifier: MIT
// Copyright (c) 2026 sonde contributors

//! Schematic generation — converts IR-1e + IR-2 into KiCad 8 `.kicad_sch`.

pub mod layout;
pub mod symbols;
pub mod wiring;

use crate::error::Error;
use crate::ir::IrBundle;
use crate::sexpr::SExpr;
use crate::uuid_gen::UuidGenerator;

/// Generate a KiCad 8 schematic from an IR bundle.
pub fn emit_schematic(bundle: &IrBundle, uuid_gen: &mut UuidGenerator) -> Result<String, Error> {
    let root = build_schematic(bundle, uuid_gen)?;
    Ok(root.serialize())
}

fn build_schematic(bundle: &IrBundle, uuid_gen: &mut UuidGenerator) -> Result<SExpr, Error> {
    let mut children = vec![
        SExpr::pair("version", "20231120"),
        SExpr::pair_quoted("generator", "sonde-kicad"),
        SExpr::pair_quoted("generator_version", env!("CARGO_PKG_VERSION")),
        SExpr::pair_quoted("uuid", &uuid_gen.next("root")),
        SExpr::pair_quoted("paper", "A4"),
        build_title_block(bundle, uuid_gen),
        build_lib_symbols(bundle)?,
    ];

    // Component instances, wires, labels
    let connectivity = wiring::build_connectivity(bundle, uuid_gen)?;

    children.extend(connectivity.instances);
    children.extend(connectivity.wires);
    children.extend(connectivity.labels);
    children.extend(connectivity.no_connects);

    Ok(SExpr::list("kicad_sch", children))
}

fn build_title_block(bundle: &IrBundle, uuid_gen: &mut UuidGenerator) -> SExpr {
    let _ = uuid_gen; // used for future deterministic date
    SExpr::list(
        "title_block",
        vec![
            SExpr::pair_quoted("title", &bundle.project),
            SExpr::pair_quoted("date", "2026-01-01"),
            SExpr::pair_quoted("rev", "1.0.0"),
            SExpr::list(
                "comment",
                vec![
                    SExpr::Atom("1".into()),
                    SExpr::Quoted(format!(
                        "Generated by sonde-kicad {}",
                        env!("CARGO_PKG_VERSION")
                    )),
                ],
            ),
        ],
    )
}

fn build_lib_symbols(bundle: &IrBundle) -> Result<SExpr, Error> {
    let registry = symbols::SymbolRegistry::new();
    let mut sym_defs = Vec::new();
    let mut seen = std::collections::HashSet::new();

    // Collect unique symbol names from IR-1e, sorted
    let mut symbol_names: Vec<&str> = bundle
        .ir1e
        .components
        .iter()
        .map(|c| c.kicad_symbol.as_str())
        .collect();
    symbol_names.sort();
    symbol_names.dedup();

    for name in symbol_names {
        if seen.insert(name) {
            let def = registry
                .get(name)
                .ok_or_else(|| Error::MissingSymbol(name.to_string()))?;
            sym_defs.push(def.clone());
        }
    }

    // Also add power symbols for power nets
    let mut power_names: Vec<String> = Vec::new();
    for net in &bundle.ir2.nets {
        if net.is_power() {
            let power_sym = symbols::power_symbol_name(&net.name);
            power_names.push(power_sym);
        }
    }
    for power_sym in &power_names {
        if !seen.contains(power_sym.as_str()) {
            seen.insert(power_sym);
            if let Some(def) = registry.get(power_sym) {
                sym_defs.push(def.clone());
            }
        }
    }

    Ok(SExpr::list("lib_symbols", sym_defs))
}
